# Generated by Django 2.0.1 on 2018-06-13 02:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyHotlineTickets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('geom_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'safety_hotline_tickets',
                'managed': False,
            },
        ),
    ]
