# Generated by Django 2.0.1 on 2018-06-13 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('crash_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crash_dt', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'crash',
                'managed': False,
            },
        ),
    ]
