# Generated by Django 2.0.1 on 2018-06-18 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_sandbox', '0002_crash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChange',
            fields=[
                ('census_block', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stops_pct_change', models.FloatField(max_length=50)),
                ('geom_polygon_4326', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'census_block_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteChange',
            fields=[
                ('shape_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pct_change', models.FloatField(max_length=50)),
                ('geom_linestring', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'route_change',
                'managed': False,
            },
        ),
    ]
