# Generated by Django 2.0.1 on 2018-06-19 17:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_sandbox', '0003_blockchange_routechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom_4326', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'sensor_locations',
                'managed': False,
            },
        ),
    ]
