# Generated by Django 2.0.1 on 2018-05-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passengercensus',
            table='passenger_census.passenger_census',
        ),
    ]
