# Generated by Django 2.0.1 on 2018-05-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0002_auto_20180522_0353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passengercensus',
            table='passenger_census',
        ),
    ]
