# Generated by Django 2.0.1 on 2018-06-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0003_auto_20180522_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRouteRollups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(blank=True, null=True)),
                ('route_number', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('service_key', models.TextField(blank=True, null=True)),
                ('total_ons', models.IntegerField(blank=True, null=True)),
                ('total_offs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annual_route_ridership',
                'managed': False,
            },
        ),
    ]
