# Generated by Django 2.0.1 on 2018-06-12 06:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0004_annualrouterollups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRouteRidership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.FloatField(blank=True, null=True)),
                ('route_number', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('service_key', models.TextField(blank=True, null=True)),
                ('total_ons', models.BigIntegerField(blank=True, null=True)),
                ('total_offs', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annual_route_ridership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrCensusBlockPolygons',
            fields=[
                ('census_block', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('geom_polygon_4326', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'or_census_block_polygons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaCensusBlockPolygons',
            fields=[
                ('census_block', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('geom_polygon_4326', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'wa_census_block_polygons',
                'managed': False,
            },
        ),
    ]
