# Generated by Django 2.0.1 on 2018-06-15 04:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0005_annualrouteridership_orcensusblockpolygons_wacensusblockpolygons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualCensusBlockRidership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.FloatField(blank=True, null=True)),
                ('census_block', models.CharField(blank=True, max_length=255, null=True)),
                ('total_ons', models.BigIntegerField(blank=True, null=True)),
                ('stops', models.BigIntegerField(blank=True, null=True)),
                ('geom_polygon_4326', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'annual_census_block_ridership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusBlockChange',
            fields=[
                ('census_block', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_ons_2009', models.BigIntegerField(blank=True, null=True)),
                ('total_ons_2017', models.BigIntegerField(blank=True, null=True)),
                ('ons_pct_change', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stops_2009', models.BigIntegerField(blank=True, null=True)),
                ('stops_2017', models.BigIntegerField(blank=True, null=True)),
                ('stops_pct_change', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom_polygon_4326', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'census_block_change',
                'managed': False,
            },
        ),
    ]
