# Generated by Django 2.0.1 on 2018-06-18 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0006_annualcensusblockridership_censusblockchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteChange',
            fields=[
                ('route_id', models.TextField(primary_key=True, serialize=False)),
                ('direction_id', models.IntegerField()),
                ('shape_id', models.TextField()),
                ('y2009_trip_count', models.IntegerField(blank=True, null=True)),
                ('y2017_trip_count', models.IntegerField(blank=True, null=True)),
                ('geom_linestring', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('pct_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_change',
                'managed': False,
            },
        ),
    ]
