# Generated by Django 2.0.1 on 2018-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_census_api', '0007_routechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRouteDifferencesForScatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('trip_count', models.IntegerField(blank=True, null=True)),
                ('frequency_change', models.FloatField(blank=True, null=True)),
                ('ons', models.IntegerField(blank=True, null=True)),
                ('ridership_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annual_route_differences_for_scatter',
                'managed': False,
            },
        ),
    ]
